Archaea
	Crenarchaeota
	Euryarchaeota
		Archaeoglobi
		Halobacteria
		Methanobacteria
			Methanomassiliicoccus
			Methanomicrobiales
				Methanocalculus
				Methanolinea
				Methanoregula
				Methanocorpusculaceae
				Methanomicrobiaceae
				Methanospirillaceae
			Methanosarcinales
				Methanosaetaceae
				Methanosarcinaceae
				Methermicoccaceae
			Methanocellales
				Methanocellaceae		
		Methanococci
		Methanomicrobia
		Methanopyri
		Nanohaloarchaea
		Thermococci
		Thermoplasmata
	Korarchaeota
	Nanoarchaeota
	Thaumarchaeota
Bacteria
Eukarya
	Animalia
		Subkingdom Parazoa
			Porifera
			Placozoa
		Subkingdom Eumetazoa
			Radiata (unranked)
				Ctenophora
				Cnidaria
		Bilateria (unranked)
			Orthonectida
			Rhombozoa
			Acoelomorpha
			Chaetognatha
			Superphylum Deuterostomia
				Chordata
					Subphylum Tunicata (Urochordata) – (tunicates; 3,000 species)
						Class Ascidiacea (sea squirts)
						Class Thaliacea (salps)
						Class Appendicularia (larvaceans)
						Class Sorberacea
					Subphylum Cephalochordata (Acraniata) – (lancelets; 30 species)
						Class Leptocardii (lancelets)
					Subphylum Vertebrata (Craniata) (vertebrates – animals with backbones; 57,674 species)
						Infraphylum incertae sedis
							Superclass 'Agnatha' paraphyletic (jawless vertebrates; 100+ species)
								Class Myxini (hagfish; 65 species)
								Class Petromyzontida or Hyperoartia (lampreys)
								Class †Conodonta
								Class †Pteraspidomorphi
								Class †Thelodonti
								Class †Anaspida
								Class †Cephalaspidomorphi
						Infraphylum Gnathostomata (jawed vertebrates)
							Superclass incertae sedis
								Class †Placodermi (Paleozoic armoured forms)
								Class Chondrichthyes (cartilaginous fish; 900+ species)
								Class †Acanthodii (Paleozoic "spiny sharks")
							Superclass Osteichthyes (bony fish; 30,000+ species)
								Class Actinopterygii (ray-finned fish; about 30,000 species)
								Class Sarcopterygii (lobe-finned fish: 8 species)
							Superclass Tetrapoda (four-limbed vertebrates; 28,000+ species)
								Class Amphibia (amphibians; 6,000 species)
								Class Reptilia (reptiles; 9,000+ species)
								Class †Synapsida (synapsids; 4,000+ species)
								Class Aves (birds; 10,000–12,000 species, nearly 22,000 subspecies)
								Class Mammalia (mammals; 5,700+ species)
									Subclass Prototheria: monotremes: echidnas and the platypus
									Subclass Theriiformes: live-bearing mammals and their prehistoric relatives
										Infraclass †Allotheria: multituberculates
										Infraclass †Triconodonta: triconodonts
										Infraclass Holotheria: modern live-bearing mammals and their prehistoric relatives
											Superlegion †Kuehneotheria
											Supercohort Theria: live-bearing mammals
												Cohort Marsupialia: marsupials
													Magnorder Australidelphia: Australian marsupials and the monito del monte
													Magnorder Ameridelphia: New World marsupials.
												Cohort Placentalia: placentals
													Magnorder Xenarthra: xenarthrans
													Magnorder Epitheria: epitheres
														Superorder Anagalida: lagomorphs, rodents, and elephant shrews
														Superorder Ferae: carnivorans, pangolins, †creodonts, and relatives
														Superorder Lipotyphla: insectivorans
														Superorder Archonta: bats, primates, colugos, and treeshrews
														Superorder Ungulata: ungulates
															Order Tubulidentata incertae sedis: aardvark
																Mirorder Eparctocyona: †condylarths, whales, and artiodactyls (even-toed ungulates)
																Mirorder †Meridiungulata: South American ungulates
																Mirorder Altungulata: perissodactyls (odd-toed ungulates), elephants, manatees, and hyraxes
				Hemichordata
				Echinodermata
				Xenoturbellida
				Vetulicolia †
			Protostomia (unranked)
				Superphylum Ecdysozoa
					Kinorhyncha
					Loricifera
					Priapulida
					Nematoda
					Nematomorpha
					Onychophora
					Tardigrada
					Arthropoda
				Superphylum Platyzoa
					Platyhelminthes
					Gastrotricha
					Rotifera
					Acanthocephala
					Gnathostomulida
					Micrognathozoa
					Cycliophora
				Superphylum Lophotrochozoa
					Sipuncula
					Hyolitha †
					Nemertea
					Phoronida
					Bryozoa
					Entoprocta
					Brachiopoda
					Mollusca
					Annelida	
	Fungi
	Amoebae
	Plantae
	Chromalveolata
	Rhizaria
	Excavata